[project]
name = "crewai-for-newbie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crewai>=0.150.0",
    "ipykernel>=6.30.0",
]
